### ISSUE TITLE
Simplify CSS

### ISSUE THREAD

**Issue by aciccarello** [aciccarello/ciccarello.me#105]
The css styles have evolved over time but are getting more out of hand

- [ ] Remove material css dependency
- [ ] Simplify typography styles
- [ ] Reorganize styles to be more reusable

**Comment by aciccarello** [comment]
Should try to do as much classless css as possible. There are a bunch of classless libraries but I'd like to take one and use only the parts I need.

Should also set up a reference page to document supported use cases. Should find balance with code as documentation. If code is simple enough could focus just on visual but could also define some code samples.

Also want to use css variables wherever possible for colors to enable theming.

References
- [mvp.css](https://andybrewer.github.io/mvp/)
- [Bahunya](https://hakanalpay.com/bahunya/)
- [CSS Tricks](https://css-tricks.com/no-class-css-frameworks/)

**Comment by aciccarello** [comment]
It might be worth reading up on the performance impacts of different css effects. For example, using system fonts over web fonts. But also things like drop shadows, scroll windows, etc.

**Comment by aciccarello** [comment]
Thinking a little about [link styles](https://www.webfx.com/blog/web-design/hyperlink-design/). Would be especially good to integrate the border-bottom vs underline trick.

Thinking about buttons vs links, I'm not sure how far I want to go with only using buttons for actions. I currently don't have many action; subscribe, sometimes a theme switcher. Buttons can be more eye catching but I also don't want to over-use them. Some people also emphasize external links (with something like an icon in ::before styles) which I might consider if it's not too obtrusive.

Some inspiration for styles:
```css
a:not(.disable-link-styles) {
  background-color: transparent;
  border-bottom: #0b0bb569 1px solid;
  text-decoration: none;
  font-weight: bold;
  color: #0b0bb5;
}

a[href^="http"]::after {
    content: "↗";
}
```
